### ISSUE TITLE
use .R suffix for R code files

### ISSUE THREAD

**Issue by tdhock** [brookesebranek/labels_research.#1]
hi @brookesebranek this is a great start! good job!!!
please use .R suffix for R code files,
For example the file currently named contigs_on_new_data_in_progress should be renamed to contigs_on_new_data_in_progress.R

**Comment by brookesebranek** [comment]
I believe I just fixed this (not 100% sure though).

**Comment by tdhock** [comment]
great! the data files now have the .R file suffix which is good.
you don't need the .R suffix for the github repository name though (labels_research.R)
